# Created with WinGet Releaser using komac v2.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: junegunn.fzf
PackageVersion: 0.66.1
PackageLocale: en-US
Publisher: Junegunn Choi
PublisherUrl: https://github.com/junegunn
PublisherSupportUrl: https://github.com/junegunn/fzf/issues
Author: Junegunn Choi
PackageName: fzf
PackageUrl: https://github.com/junegunn/fzf
License: MIT
LicenseUrl: https://github.com/junegunn/fzf/blob/HEAD/LICENSE
Copyright: Copyright (c) 2013-2023 Junegunn Choi
CopyrightUrl: https://github.com/junegunn/fzf/blob/master/LICENSE
ShortDescription: A general-purpose command-line fuzzy finder
Tags:
- cli
- go
ReleaseNotes: |-
  - Bug fixes
    - Fixed a bug preventing 'ctrl-h' from being bound to an action (#4556)
    - Fixed --no-color / NO_COLOR theme (#4561)
ReleaseNotesUrl: https://github.com/junegunn/fzf/releases/tag/v0.66.1
ManifestType: defaultLocale
ManifestVersion: 1.10.0
